server:
  port: 8001
  name: elyte
  error:
    whitelabel:
      enabled: false
    path: /error

---
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: [ "openapi", "swagger-ui" ]
  server:
    port: 9001

---

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){yellow} %clr([%level]){red}  %c{1.} [%t] %m%n'
  level:
    root: INFO
    org:
      springframework: INFO
      
---

springdoc:
  show-actuator: true
  use-management-port: false
  swagger-ui:
    enabled: true
    operationsSorter: method
    path: /docs
    disable-swagger-default-url: true
    validatorUrl: null
    syntaxHighlight:
      activated: true
  api-docs:
    enabled: true
   
---

spring:
  servlet:
    multipart:
      max-file-size: '10MB'
      max-request-size: '10MB'
      resolve-lazily: true

  mail:
    templates:
      path: templates
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: 'elyte5star'
    password: ${MAIL_PASSWORD:vqynttjhqmfblupu}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          startttls:
            enable: true

  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


  # Message Broker
  rabbitmq:
    host: ${RABBIT_HOST:rabbitQ}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:rabbitUser}
    password: ${RABBITMQ_DEFAULT_PASS:elyteRQ}

  # Maximum time static resources should be cached
  web:
    resources:
      add-mapping: false
      cache:
        cachecontrol:
          max-age: 12h

  #===============================
  # DATA SOURCE
  #===============================
  datasource:
    url: jdbc:mariadb://localhost:3306/elyte
    username: userExample
    password: 54321
    driver-class-name: org.mariadb.jdbc.Driver

    #Keep the connection alive if idle for a long time (needed in production)
    tomcat:
      testOnBorrow: true
      validationQuery: SELECT 1

    # ===============================
    # = JPA / HIBERNATE
    # ===============================
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      
---

api:
  module-name: 'Interactive Documentation for e-Market'
  version: '1.0.1'
  jwt:
    secret: ${JWT_SECRET:7a3c54660456ff1137b652e498624dfa09a0ec12b4fc49d38b85465da15027a1}
  cipher:
    secret: ${CIPHER_SECRET:8a3b7aee84b1856e0f786d7e938ce8908a551779c6b6ceecf92e726e97ef98df}
    salt: ${CIPHER_SALT:7409412499eaa142810374d343ae17f988a99809be4bf42fb79b474d7a198c79}

---
attachment:
  invoice: 'path_to_file'