package com.elyte.domain.enums;

public enum  EmailType {
    GENERAL_INFO,
    RESET_USER_PASSWORD,
    CUSTOMER_ENQUIRY,
    NEW_USER_OTP_VERIFICATION,
    NEW_DEVICE_LOGIN,
    NEW_USER_ACCOUNT_CONFIRMATION,
    WITH_ATTACHMENT,
    UNUSUAL_LOCATION_LOGIN;
    
}
